config/routes.rb
Grassroots::Application.routes.draw do

  devise_for :users

  resources :categories
  resources :users
  resources :ideas

  match 'vote' => 'grassroots#vote'
  match 'new_idea' => 'grassroots#new_idea'
  match 'new_comment' => 'grassroots#new_comment'
  match 'delete_comment' => 'grassroots#delete_comment'
  match 'about' => 'grassroots#about'
  
  root :to => 'grassroots#index'
  match 'ideas/:id/:name' => 'ideas#show'
  

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :idea_vote, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  
  def category_name
    category.name if category
  end
  
  def user_alias
    user.alias if user
  end
  
  def vote_tally
    yae_votes - nay_votes
  end
  
  def total_votes
    yae_votes + nay_votes
  end
  
  def calculate_rank
    hot
  end
  
  def seo_url
    "#{id}/#{subject.parameterize}"
  end
  

  def epoch_seconds
    epoch = DateTime.new(1970, 1, 1)
    
    if created_at 
      td = created_at - epoch
    else
      td = DateTime.now - epoch
    end
    
    return td.seconds #td.days.round * 86400 + td.seconds / 1000000
    
  end

  def score
    2 * yae_votes - nay_votes
  end

  def hot
    s = vote_tally
    l = [s.abs, 1].max
    order = Math.log10(l)
    if s > 0
      sign = 1
    elsif s < 0
      sign = -1
    else
      sign = 0
    end
    
    seconds = epoch_seconds - 1134028003
    score = order + sign * seconds / 180000
    
    logger.debug "**** CALCULATING SCORE ****"
    logger.debug "score: #{s}"
    logger.debug "order: #{order}"
    logger.debug "seconds: #{seconds}"
    logger.debug "score: #{score}"

    
    return score
  end
      
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    
    limit = 15
    if params[:category_id]
      @ideas = Idea.where(:category_id => params[:category_id]).order("rank DESC").limit(limit)
    elsif params[:category_type]
      if params[:category_type] == "top"
        @ideas = Idea.order("rank DESC").limit(limit)
      elsif params[:category_type] == "new"
        @ideas = Idea.order("created_at DESC").limit(limit)
      end
    else 
      @ideas = Idea.order("rank DESC").limit(limit)
    end

    if (params[:layout])
      render :layout => params[:layout]
    else
      respond_to do |format|
        format.html
        format.json { 
          render :json => @ideas.to_json(:methods => [:vote_tally, :category_name, :user_alias, :seo_url]) 
        }
      end
    end
    


  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    
    @idea = Idea.find(params[:id])
    @votes = IdeaVote.where(:idea_id => params[:id]);
    @comments = Comment.where(:idea_id => params[:id]).roots;
    
    @tab_name = @idea.category_name
    @show_facebook = true;
    @page_title = 'Grassroots Policy: ' + @idea.subject
    
    respond_to do |format|
      format.html { render }
      format.json { render :json => @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @idea }
      
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
    @tab_name = @idea.category_name
    
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])
    @idea.user_id = current_user.id
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, :notice => 'Idea was successfully created.' }
        format.json { render :json => @idea, :status => :created, :location => @idea }
      else
        format.html { render :action => "new" }
        format.json { render :json => @idea.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])
    if current_user.alias == "Rob" || @idea.user_id = current_user.id

      respond_to do |format|
        if @idea.update_attributes(params[:idea])
          format.html { redirect_to @idea, :notice => 'Idea was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @idea.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    if current_user.alias == "Rob"
      @idea = Idea.find(params[:id])
      @idea.destroy

      respond_to do |format|
        format.html { redirect_to ideas_url }
        format.json { head :ok }
      end
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>

  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
	<%= f.text_area :description %>
  </div>

  <div class="actions">
    <input id="save" name="commit" type="submit" value="Update Idea">&nbsp;
	<%= link_to 'Cancel', @idea, :id => "back" %>
  </div>

<% end %>

<script>
	
	$(function () {
		$('#save').button();
		$('#back').button();
	})
	
</script>

app/views/ideas/edit.html.erb
<%= render 'form' %>

app/views/ideas/index.html.erb
<% @ideas.each do |idea| %>
<%= render 'shared/idea', :idea => idea %>	
<% end %>

<%= link_to 'New Idea', new_idea_path, :class => 'new-idea', 'category_id' => params[:category_id] %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<% content_for :meta do %>
	<meta property="og:title" content="Grassroots Policy: <%= @idea.subject %>" />
	<meta property="og:site_name" content="Grassroots Policy"/>
	<meta property="fb:admins" content="robert.recalde"/>
	<meta property="og:description" content="<%= @idea.description %>"/>
<% end %>

<%= render 'shared/idea', :idea => @idea %>

<div class="idea ui-corner-all">
	<div class="idea-body">
		<div class="idea-subject">
			Votes:
		</div>
		<div class="idea-text">
		<% @votes.each do |vote| %>
			<span class="user-<%= vote.vote %>">
				<%= vote.user_alias %>
			</span> 
		<% end %>
		</div>
	</div>
</div>
<%= render 'shared/comments', :comments => @comments unless @comments.empty? %>
<br/>
<a id="root_comment" href="#" class="idea-button">Comment</a>&nbsp;
<a id="back_button" href="/" class="idea-button">Back</a>

<script>
	
	$(function () { 


		var ideas = $('.idea');
		linkify(ideas);
		
		var comments = $('.comment-body');
		linkify(comments);
		
		$('.idea-button').button();
				
		<% if user_signed_in? %>
		
		$('.vote-yea').click(function() {
			vote(<%= @idea.id %>, 'yae', function(data) {
				location.reload(true)
			});
		});
		
		$('.vote-nay').click(function(){
			vote(<%= @idea.id %>, 'nay', function(data) {
				location.reload(true);
			});
		});
		
		$('.reply-link').click(function() {
			var comment = $(this).parent().parent();
			var comment_id = comment.attr('comment_id');
			var idea_id = comment.attr('idea_id');
			var comment_text = $(this).html();
			new_comment(idea_id, comment_id, comment_text);
		});
		
		$('#root_comment').click(function() {
			new_comment(<%= @idea.id %>, null, null);
			return false;
		});
		
		$('.delete-comment').click(function() {
			var comment = $(this).parent().parent();
			var comment_id = comment.attr('comment_id');
			delete_comment(comment_id);
			return false;
		});
		
		<% else %>
		
		$('.vote-yea').click(login_dialog);
		$('.vote-nay').click(login_dialog);
		$('.idea-comment').click(login_dialog);
		$('#root_comment').click(login_dialog);
		$('.reply-link').click(login_dialog);
		
		<% end %>
	});
</script>