config/routes.rb
Grassroots::Application.routes.draw do

  devise_for :users

  resources :categories
  resources :users
  resources :ideas

  match 'vote' => 'grassroots#vote'
  match 'new_idea' => 'grassroots#new_idea'
  match 'new_comment' => 'grassroots#new_comment'
  match 'delete_comment' => 'grassroots#delete_comment'
  match 'about' => 'grassroots#about'
  
  root :to => 'grassroots#index'
  match 'ideas/:id/:name' => 'ideas#show'
  

end

app/views/shared/_comments.html.erb
<% comments.each do |comment| %>
	<div class="comment" idea_id="<%= comment.idea_id %>" comment_id="<%= comment.id %>">
		<div class="comment-user">
			Posted by <%= comment.user_alias %> (<%= time_ago_in_words(comment.created_at) %> ago)
		</div>
		<div class="comment-body">
			<%= comment.comment %>
		</div>
		<div class="comment-actions">
			<a href="#" class="reply-link">Reply</a>
			<% if user_signed_in? && current_user.alias == "Rob" %>
			&nbsp;<a href="#" class="delete-comment">Delete</a>
			<% end %>
		</div>
		<% if !comment.leaf? %>
		<div class="comment-children">
			<%= render 'shared/comments', :comments => comment.children %>
		</div>
		<% end %>
	</div>
<% end %>

app/views/shared/_idea.html.erb
<!-- Idea: <%= idea.id %> -->
<div class="idea ui-corner-all" idea_id="<%= idea.id %>">
	<div class="idea-vote ui-corner-all">
		<div class="vote-yea">Yea</div>
		<div class="vote-count"><%= idea.vote_tally %></div>
		<div class="vote-nay">Nay</div>
	</div>
	<div class="idea-body">
		<div class="idea-subject">
			<a href="/ideas/<%= idea.seo_url %>"><%= idea.subject %></a>
		</div>
		<div class="idea-text">
			<%= idea.description %>
		</div>
		<div class="idea-user">
			Posted by <%= idea.user_alias %> to <%= idea.category_name %> (<%= time_ago_in_words(idea.created_at) %> ago)
			<% if @show_facebook %>
				&nbsp;<a name="fb_share"></a>
			<% end %>
		</div>
		<% if user_signed_in? && current_user.alias == "Rob" %>
		<div class="idea-buttons">
			<%= link_to 'Edit', edit_idea_path(idea) %>&nbsp;
		    <%= link_to 'Delete', idea, :confirm => 'Are you sure?', :method => :delete %>
		</div>
		<% end %>
	</div>
	<div class="idea-clear"></div>
</div>

app/views/shared/_meta.html.erb
<meta property="og:title" content="Grassroots Policy" />
<meta property="og:site_name" content="Grassroots Policy"/>
<meta property="fb:admins" content="robert.recalde"/>
<meta property="og:description" content="Add your voice to our democracy."/>